// lib/qwik/src/index.tsx
import { Fragment, component$, h, useStore } from "@builder.io/qwik";

export const Index = component$((props) => {
  const state = useStore({ time: "daily" });

  return (
    <Fragment>
      Report for Jeremy Robson
      <button onClick$={(event) => (state.time = "daily")}>Daily</button>
      <button onClick$={(event) => (state.time = "weekly")}>Weekly</button>
      <button onClick$={(event) => (state.time = "monthly")}>Monthly</button>
      Work 5hrs Previous - 7hrs 32hrs Previous - 36hrs 103hrs Previous - 128hrs
      Play 1hr Previous - 2hrs 10hrs Previous - 8hrs 23hrs Previous - 29hrs
      Study 0hrs Previous - 1hr 4hrs Previous - 7hrs 13hrs Previous - 19hrs
      Exercise 1hr Previous - 1hr 4hrs Previous - 5hrs 11hrs Previous - 18hrs
      Social 1hr Previous - 3hrs 5hrs Previous - 10hrs 21hrs Previous - 23hrs
      Self Care 0hrs Previous - 1hr 2hrs Previous - 2hrs 7hrs Previous - 11hrs{" "}
    </Fragment>
  );
});

export default Index;

// lib/reactNative/src/index.tsx
import * as React from "react";
import {
  FlatList,
  ScrollView,
  View,
  StyleSheet,
  Image,
  Text,
} from "react-native";

function Index(props) {
  const state = useLocalProxy({ time: "daily" });

  return (
    <>
      <Text>Report for Jeremy Robson</Text>
      <View onClick={(event) => (state.time = "daily")}>
        <Text>Daily</Text>
      </View>

      <View onClick={(event) => (state.time = "weekly")}>
        <Text>Weekly</Text>
      </View>

      <View onClick={(event) => (state.time = "monthly")}>
        <Text>Monthly</Text>
      </View>
      <Text>Work 5hrs </Text>
      <Text>Previous - 7hrs </Text>
      <Text>32hrs </Text>
      <Text>Previous - 36hrs </Text>
      <Text>103hrs </Text>
      <Text>Previous - 128hrs </Text>
      <Text>Play 1hr </Text>
      <Text>Previous - 2hrs </Text>
      <Text>10hrs </Text>
      <Text>Previous - 8hrs </Text>
      <Text>23hrs </Text>
      <Text>Previous - 29hrs </Text>
      <Text>Study 0hrs </Text>
      <Text>Previous - 1hr </Text>
      <Text>4hrs </Text>
      <Text>Previous - 7hrs </Text>
      <Text>13hrs </Text>
      <Text>Previous - 19hrs </Text>
      <Text>Exercise 1hr </Text>
      <Text>Previous - 1hr </Text>
      <Text>4hrs </Text>
      <Text>Previous - 5hrs </Text>
      <Text>11hrs </Text>
      <Text>Previous - 18hrs </Text>
      <Text>Social 1hr </Text>
      <Text>Previous - 3hrs </Text>
      <Text>5hrs </Text>
      <Text>Previous - 10hrs </Text>
      <Text>21hrs </Text>
      <Text>Previous - 23hrs </Text>
      <Text>Self Care 0hrs </Text>
      <Text>Previous - 1hr </Text>
      <Text>2hrs </Text>
      <Text>Previous - 2hrs </Text>
      <Text>7hrs </Text>
      <Text>Previous - 11hrs </Text>
    </>
  );
}

export default Index;
